tests added
SonarSource/sonarlint-omnisharp pull request #141
Opened 2022-11-04 12:30 UTC by ugras-ergun-sonarsource

2022-11-04 12:31 UTC, ugras-ergun-sonarsource commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/IQuickFix.cs
> +        IList<IFix> Fixes { get; }
I've changed these to Ilist to be able to add items.

2022-11-04 12:33 UTC, ugras-ergun-sonarsource commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProvider.cs
> +        internal delegate Task<(Solution Solution, IEnumerable<FileOperationResponse> FileChanges)>
Because "GetFileChangesAsync" is in the base class and can not be mocked after having discussion with rita decided to add a delegate as a constructor parameter and pass to it in tests

2022-11-04 12:35 UTC, ugras-ergun-sonarsource commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProvider.cs
> +            null
GetFileChangesAsync is an instance method so the method wrapping should not be static and we can't pass non-static members. So I am doing a null check in the internal constructor to use the default value.

2022-11-04 12:38 UTC, ugras-ergun-sonarsource commented on omnisharp-dotnet/src/Services.UnitTests/TestingInfrastructure/TestableCodeAction.cs
> +    internal class TestableCodeAction : CodeAction
Because code action is an abstract class we can not mock it so I've created a mock class.

2022-11-04 12:39 UTC, ugras-ergun-sonarsource commented on omnisharp-dotnet/src/Services.UnitTests/TestingInfrastructure/TestableCodeAction.cs
> +        protected override async Task<IEnumerable<CodeActionOperation>> ComputeOperationsAsync(CancellationToken cancellationToken)
This is to "GetOperationsAsync" but unfortunately I had to go down to this method which was virtual and did not have any internal parameters.

2022-11-04 13:07 UTC, rita-sonarsource commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/IQuickFix.cs
> +        IList<IFix> Fixes { get; }
The whole point of the readonly was so you could not add items. Why not just mock it to return whatever you need?

2022-11-04 13:12 UTC, ugras-ergun-sonarsource commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/IQuickFix.cs
> +        IList<IFix> Fixes { get; }
Yeah and apparently I've changed the code where I needed to add things.

2022-11-07 13:54 UTC, rita-sonarsource commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProvider.cs
> +        private readonly GetFileChangesAsyncFnc getFileChangesAsyncFnc;
cosmetics: maybe with a "u" in Func? I believe that's the standard

2022-11-07 13:58 UTC, rita-sonarsource commented on omnisharp-dotnet/src/Services.UnitTests/TestingInfrastructure/TestableCodeAction.cs
> +    internal class TestableCodeAction : CodeAction
I think it should be as a private class next to the code that needs it. We shouldn't reference CodeAction object anywhere else because it's so complicated.

2022-11-07 14:02 UTC, rita-sonarsource commented on omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProviderTests.cs
> +            var operation = new ApplyChangesOperation(workspace.CurrentSolution);
`operation` is not used anywhere besides passing it to CreateCodeAction: can we simplify CreateCodeAction to receive the solution and do the orchestration inside? it would simplify reading

2022-11-07 14:04 UTC, rita-sonarsource commented on omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProviderTests.cs
> +            var operation = new ApplyChangesOperation(workspace.CurrentSolution);
Perhaps also a check what happens if the operation is not ApplyChangesOperation?

2022-11-07 14:04 UTC, rita-sonarsource commented on omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProviderTests.cs
> +            var textChange = CreateTextChange("New Text", 1, 2, 3, 4);
it would help to add the parameter names

2022-11-07 14:06 UTC, rita-sonarsource commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProvider.cs
>                  foreach (var operation in operations.OfType<ApplyChangesOperation>())
We have no unit tests of multiple ApplyChangesOperation. 
Perhaps we should instead do SingleOrDefault and assert that it's not null?

2022-11-07 14:06 UTC, rita-sonarsource commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProvider.cs
> +        private GetFileChangesAsyncFnc GetFileChangesAsyncFncImpl()
cosmetics: missing empty line

2022-11-07 14:07 UTC, rita-sonarsource commented on omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProviderTests.cs
> +
cosmetics: extra empty line

2022-11-07 14:07 UTC, rita-sonarsource commented on omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProviderTests.cs
>          private DiagnosticQuickFixesProvider CreateTestSubject(
cosmetics: missing empty line

2022-11-07 14:07 UTC, rita-sonarsource commented on omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProviderTests.cs
> +        private Mock<ISonarLintDiagnosticCodeActionsProvider> CreateDiagnosticCodeActionsProvider(
cosmetics: missing empty line

2022-11-07 14:07 UTC, rita-sonarsource commented on omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProviderTests.cs
> +        private TestableCodeAction CreateCodeAction(string title, ApplyChangesOperation operation)
cosmetics: missing empty line

2022-11-07 14:08 UTC, rita-sonarsource commented on omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProviderTests.cs
> +        private static ModifiedFileResponse CreateFileResponse(string fileName,
cosmetics: missing empty line

2022-11-07 14:09 UTC, rita-sonarsource commented on omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProviderTests.cs
> +        private DiagnosticQuickFixesProvider.GetFileChangesAsyncFnc GetFileChangesAsyncMock(Solution solution,
This should be a mock + verify that it was called with the right params

2022-11-07 14:10 UTC, rita-sonarsource commented on omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProviderTests.cs
> +            return diagnosticCodeActionsProvider;
Cosmetics: new line before return

2022-11-07 14:10 UTC, rita-sonarsource commented on omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProviderTests.cs
> +            return textChange;
Cosmetics: new line before return

2022-11-07 14:11 UTC, rita-sonarsource commented on omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProviderTests.cs
> +            return fileResponse;
Cosmetics: new line before return

2022-11-07 14:11 UTC, duncanp-sonar commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProvider.cs
> +        private readonly GetFileChangesAsyncFnc getFileChangesAsyncFnc;
FWIW I don't normally have "Func" on the end - it's clear from the method signature. I'd just call it `GetFileChangesAsync`.

2022-11-07 14:11 UTC, rita-sonarsource requested changes
@ugras-ergun-sonarsource looks good, see my comments (and my cosmetic comments 😜 )

2022-11-07 14:26 UTC, duncanp-sonar commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProvider.cs
> +            this.getFileChangesAsyncFnc = getFileChangesAsyncFnc ?? GetFileChangesAsyncFncImpl();
#Can't the constructor just reference the `GetFileChangesAsync` method directly? e.g.

```
//this.getFileChangesAsyncFnc = getFileChangesAsyncFnc ?? GetFileChangesAsyncFncImpl();

this.getFileChangesAsyncFnc = getFileChangesAsyncFnc ?? GetFileChangesAsync;
```

2022-11-07 14:27 UTC, duncanp-sonar commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProvider.cs
> +        private GetFileChangesAsyncFnc GetFileChangesAsyncFncImpl()
(...although the method might not be needed)

2022-11-07 14:29 UTC, duncanp-sonar commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProvider.cs
> +        internal delegate Task<(Solution Solution, IEnumerable<FileOperationResponse> FileChanges)>
I think it's worth commenting explicitly that this delegate was introduced to allow tests to replace the behaviour of the base class - it will save some time for anyone who has to look at this in the future.

2022-11-07 15:02 UTC, duncanp-sonar commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProvider.cs
>                  foreach (var operation in operations.OfType<ApplyChangesOperation>())
As discussed offline, I think there's a preceding problem, namely that we filter out any changes that are not `ApplyChangesOperation`. Presumably all of the operations in the code action need to be executed for it to make sense, not just some of them.

If we only support simple edits to the current file currently, we could remove the filter **and** @rita-sonarsource's suggestion i.e. we'll only apply the fix if there is only one operation and it is of type `ApplyChangesOperation`.

(alternatively, if we think we can handle multiple `ApplyChangesOperation`s then we could include the fix if all of its operations are of type `ApplyChangeOperation`, but then we'd need a test for it as @rita-sonarsource suggests).

2022-11-07 15:04 UTC, duncanp-sonar commented on omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProviderTests.cs
> +        public async Task GetDiagnosticQuickFixes_DiagnosticHasCodeActionswithMultipleEdits_ReturnsQuickFixes()
Naming: this test only has one `CodeAction` so it should be `..._DiagnosticHasCodeActionWithMultipleEdits...`.

2022-11-07 15:07 UTC, duncanp-sonar commented on omnisharp-dotnet/src/Services.UnitTests/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProviderTests.cs
> +        public async Task GetDiagnosticQuickFixes_DiagnosticHasCodeActionswithMultipleEdits_ReturnsQuickFixes()
Missing test case: a diagnostic with two different code actions.
Ideally the new test would check that the first code fix in each action is given the same solution instance i.e. a "clean" solution is used each time.

2022-11-07 16:26 UTC, ugras-ergun-sonarsource commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProvider.cs
> +        private readonly GetFileChangesAsyncFnc getFileChangesAsyncFnc;
GetFileChangesAsync is the name of the method in the base class and if we name it that way it would create a conflict.

2022-11-09 12:31 UTC, ugras-ergun-sonarsource commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProvider.cs
> -                var solution = workspace.CurrentSolution;
after the changes, there was no need to have variables so I have simplified the code.

2022-11-09 18:01 UTC, duncanp-sonar commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProvider.cs
> +                Debug.Assert(applyChangesOperations.Count <= 1);
It's always better to include a message in an assertion. I you don't have a debugger attached, the dialogue that pops up isn't that helpful, as it just shows the call stack.

2022-11-09 18:03 UTC, duncanp-sonar commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProvider.cs
> +                Debug.Assert(fileChangesResult.FileChanges.All(c => c is ModifiedFileResponse));
Missing assertion message.

2022-11-09 18:06 UTC, duncanp-sonar commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProvider.cs
> +                var applyChangesOperations = operations.OfType<ApplyChangesOperation>().ToList();
This logic has changed back from what @rita-sonarsource [shared](https://github.com/SonarSource/sonarlint-omnisharp/pull/136/commits/be5fc23122c1b182a027c0cac14f70b4dcd791f6) this morning - it's now back to the more-unsafe version of ignoring any non-`ApplyChangesOperations`.

The safer approach is the one in Rita's version: only apply the fix if there is only one operation, and that operation is of type `ApplyChangesOperation`.

2022-11-10 10:23 UTC, rita-sonarsource commented
@duncanp-sonar please re-review

2022-11-10 16:33 UTC, duncanp-sonar commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProvider.cs
> +                    throw new ArgumentOutOfRangeException(nameof(operations), "Expecting quick fixes to contain one or zero operations.");
Throwing is pretty strong - throwing here will mean no diagnostics or fixes for the current file (?)

Your [version from yesterday](https://github.com/SonarSource/sonarlint-omnisharp/pull/136/commits/be5fc23122c1b182a027c0cac14f70b4dcd791f6) just skipped that particular fix.

Would a `Debug.Assert` be enough?

2022-11-10 16:34 UTC, duncanp-sonar commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProvider.cs
> +                Debug.Assert(fileChangesResult.FileChanges.All(c => c is ModifiedFileResponse));
The dialogue popped up by VS is more useful if the assertion has a message.

2022-11-10 16:56 UTC, duncanp-sonar approved these changes
Looks good - just the one question about whether throwing is too strong.

2022-11-11 09:10 UTC, rita-sonarsource commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProvider.cs
> +                    throw new ArgumentOutOfRangeException(nameof(operations), "Expecting quick fixes to contain one or zero operations.");
I'm not sure. If it's a debug.assert, we won't likely ever see it in production and it won't work properly. I think it's better to leave the exception so that we would at least know if we're wrong in our assumption.

2022-11-11 09:21 UTC, rita-sonarsource commented
@duncanp-sonar I will merge this with the exception throwing for now, so I could start working on the conflicts of the other PRs. I will fix this to debug assert later if we decide to do it.

2022-11-11 09:22 UTC, merged

2022-11-11 09:31 UTC, duncanp-sonar commented on omnisharp-dotnet/src/Services/DiagnosticWorker/QuickFixes/DiagnosticQuickFixesProvider.cs
> +                    throw new ArgumentOutOfRangeException(nameof(operations), "Expecting quick fixes to contain one or zero operations.");
An exception in production makes the experience worse for users (no diagnostics for the whole file), but there's no guarantee it would be reported. I'm leaning towards impacting the user as little as possible e.g. assert, and log a message, so that only "incompatible" fixes are ignored.