Update to OmniSharp-Roslyn 1.39.10
SonarSource/sonarlint-omnisharp pull request #184
Opened 2023-12-12 10:43 UTC by nquinquenel

2023-12-12 10:55 UTC, thahnen commented on its/pom.xml
> -              <url>https://repox.jfrog.io/artifactory/sonarsource/org/sonarsource/sonarlint/omnisharp/omnisharp-roslyn/1.39.6/omnisharp-roslyn-1.39.6-net6.zip</url>
We have to update our fork, let's take a look at that later sometime.

2023-12-12 10:55 UTC, thahnen commented on its/src/test/java/org/sonarsource/sonarlint/omnisharp/its/OmnisharpIntegrationTests.java
> +    ClientInputFile inputFile = prepareInputFile(baseDir, "DotNet8Project/Program.cs",
Actually, Sophio noticed that this is not necessary, if we provide `null` then the actual file is used. This is just to have one file you modify over time.

2023-12-12 10:55 UTC, thahnen commented on its/src/test/java/org/sonarsource/sonarlint/omnisharp/its/OmnisharpIntegrationTests.java
> +      .putExtraProperty("sonar.cs.internal.useNet6", "true")
Why .NET6?

2023-12-12 10:56 UTC, thahnen commented on omnisharp-dotnet/build/DownloadOmniSharp.targets
> -    <OmniSharpZipUrl>https://repox.jfrog.io/artifactory/sonarsource/org/sonarsource/sonarlint/omnisharp/omnisharp-roslyn/$(OmniSharpVersion)/omnisharp-roslyn-$(OmniSharpVersion)-net472.zip</OmniSharp
Same as above

2023-12-12 10:56 UTC, thahnen commented on omnisharp-dotnet/src/Services/DiagnosticWorker/OmniSharp/CopiedCSharpDiagnosticWorker.cs
> +        public ImmutableArray<DocumentId> QueueDocumentsForDiagnostics(IEnumerable<Document> documents, AnalyzerWorkType workType)
For that maybe ask Pavel, I think he knows what this might be for.

2023-12-12 13:49 UTC, nquinquenel commented on its/src/test/java/org/sonarsource/sonarlint/omnisharp/its/OmnisharpIntegrationTests.java
> +    ClientInputFile inputFile = prepareInputFile(baseDir, "DotNet8Project/Program.cs",
This does not work if I replace by null in most test cases

2023-12-13 09:46 UTC, henryju commented on its/src/test/java/org/sonarsource/sonarlint/omnisharp/its/OmnisharpIntegrationTests.java
> +      .putExtraProperty("sonar.cs.internal.useNet6", "true")
This property controls whether we should use the old ".Net framework"/"mono" build of OmniSharp, or the new ".NET Core" one.

2023-12-13 09:57 UTC, nquinquenel commented on omnisharp-dotnet/src/Services/DiagnosticWorker/OmniSharp/CopiedCSharpDiagnosticWorker.cs
> +        public ImmutableArray<DocumentId> QueueDocumentsForDiagnostics(IEnumerable<Document> documents, AnalyzerWorkType workType)
Given the logic of the class, and based on the official OmniSharp-Roslyn [implementation](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Roslyn.CSharp/Workers/Diagnostics/CSharpDiagnosticWorkerWithAnalyzers.cs#L396), I think the new changes I made make sense 😄

2023-12-13 12:48 UTC, thahnen commented on its/src/test/java/org/sonarsource/sonarlint/omnisharp/its/OmnisharpIntegrationTests.java
> +      .putExtraProperty("sonar.cs.internal.useNet6", "true")
Ah okay, was a bit irritated by the naming of the property ^^

2023-12-14 07:48 UTC, thahnen requested changes
The JFrog artifacts are now available, you chan change them 😄

2023-12-14 07:48 UTC, thahnen commented on its/pom.xml
> +              <url>https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.10/omnisharp-linux-x64-net6.0.zip</url>
```suggestion
              <url> https://repox.jfrog.io/artifactory/sonarsource/org/sonarsource/sonarlint/omnisharp/omnisharp-roslyn/1.39.10/omnisharp-roslyn-1.39.10-net6.zip </url>
```

2023-12-14 07:48 UTC, thahnen commented on omnisharp-dotnet/build/DownloadOmniSharp.targets
> -    <OmniSharpZipUrl>https://repox.jfrog.io/artifactory/sonarsource/org/sonarsource/sonarlint/omnisharp/omnisharp-roslyn/$(OmniSharpVersion)/omnisharp-roslyn-$(OmniSharpVersion)-net472.zip</OmniSharp
Revert this change, it should now work correctly and use 1.39.10, it was uploaded by RE

2023-12-18 20:02 UTC, nquinquenel commented
Hey @pavel-mikula-sonarsource, I tried to update SonarLint OmniSharp to omnisharp-roslyn 1.39.10 (we used 1.39.6). Could you have a quick look as a C# expert if anything seems off to you, thanks!

2023-12-19 08:18 UTC, henryju approved these changes

2023-12-19 08:22 UTC, thahnen approved these changes
Looks good to me, even though I can only roughly review the C# part.

2023-12-19 08:48 UTC, merged